# Generated by Django 5.0.6 on 2024-07-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("singer", "0003_alter_song_singer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="singer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="singer",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="song",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="song",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="singer",
            name="tag",
            field=models.ManyToManyField(blank=True, to="singer.tag"),
        ),
    ]
